# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SaveAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'balance': 'int'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'balance': 'balance'
    }

    def __init__(self, name=None, type=None, balance=None):  # noqa: E501
        """SaveAccount - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._balance = None
        self.discriminator = None
        self.name = name
        self.type = type
        self.balance = balance

    @property
    def name(self):
        """Gets the name of this SaveAccount.  # noqa: E501

        The name of the account  # noqa: E501

        :return: The name of this SaveAccount.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SaveAccount.

        The name of the account  # noqa: E501

        :param name: The name of this SaveAccount.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this SaveAccount.  # noqa: E501

        The account type  # noqa: E501

        :return: The type of this SaveAccount.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SaveAccount.

        The account type  # noqa: E501

        :param type: The type of this SaveAccount.  # noqa: E501
        :type: str
        """
        allowed_values = ["checking", "savings", "creditCard", "cash", "lineOfCredit", "otherAsset", "otherLiability"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def balance(self):
        """Gets the balance of this SaveAccount.  # noqa: E501

        The current balance of the account in milliunits format  # noqa: E501

        :return: The balance of this SaveAccount.  # noqa: E501
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """Sets the balance of this SaveAccount.

        The current balance of the account in milliunits format  # noqa: E501

        :param balance: The balance of this SaveAccount.  # noqa: E501
        :type: int
        """

        self._balance = balance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
